class Constants:
    
    OK_STATUS_TEXT: str = 'OK_STATUS'
    BAD_REQUEST_TEXT: str = 'BAD_REQUEST_STATUS'
    NOT_FOUND_TEXT: str = 'NOT_FOUND_STATUS'
    INTERNAL_SERVER_TEXT: str = 'INTERNAL_SERVER_ERROR'
    CREATED_STATUS_TEXT: str = 'CREATED_STATUS'